//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.04 at 03:01:11 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.gama.com/TableWS")
package com.gama.tablews;

